### ISSUE TITLE
Custom sequence allocationSize not generated in the domain files

### ISSUE THREAD

**Issue by jaydubu** [jaxio/pack-backend-jpa#2] opened 2016-01-23 17:26 UTC
I have configured the sequence allocationSize in celerio-maven-plugin.xml, but it is missing from the generated @SequenceGenerator in the domain code.
## celerio-maven-plugin.xml

<sequences>
    <sequence tableNamePattern="*" sequenceName="{TABLE_NAME}_ID_SEQ" allocationSize="10" />
</sequences>
## Domain java code

@Override
@Column(name = "ID", precision = 38)
@GeneratedValue(strategy = SEQUENCE, generator = "ACCOUNT_ID_SEQ")
@Id
@SequenceGenerator(name = "ACCOUNT_ID_SEQ", sequenceName = "ACCOUNT_ID_SEQ")
public Long getId() {
    return id;
}

Thanks!

**Comment by jaydubu** [comment] 2016-01-23 18:04
The sample sequence config is missing from my original post...

##celerio-maven-plugin.xml

``` xml
<sequences>
    <sequence tableNamePattern="*" sequenceName="{TABLE_NAME}_ID_SEQ" allocationSize="10" />
</sequences>
```

**Comment by nromanetti** [comment] 2016-01-23 21:15
You closed it, I guess it worked out ?

**Comment by jaydubu** [comment] 2016-01-23 23:31
I clicked the close button by mistake :)

**Comment by nromanetti** [comment] 2016-01-24 17:49
I could not reproduce it.
Beware Celerio is not going to overwrite the generated entity file if you edit it manually. In such case it generates it under the target folder... my guess is that you edited the generated file manually, then you changed the conf and regenerate... try to delete the generated entity and regenerate.

**Comment by jaydubu** [comment] 2016-01-25 07:56
I am still having the same issue.  I have tried deleting src/main/generated-java before regenerating, and I have also tried creating new empty project and generating the code from fresh.

I am using an Oracle database, I am not sure if that matters though.

**Comment by mreddimasi** [comment] 2016-01-25 14:30
Also, the sequence configured {TABLE_ID_SEQ} is not taken into consideration, i.e, if we've configured the sequence in Oracle DB, the sequence is never incremented when we add an entity. But the ID column does have the correct values of sequence from 1... n while respecting the allocationSize

**Comment by nromanetti** [comment] 2016-01-25 14:54
This is a different issue, may be you should specify the schema or catalog in the SequenceGenerator, Celerio config does not support it (I'll make sure it does in next release). You can try manually in the mean time that would be helpful.
Regarding the allocationSize, I still cannot reproduce your issue and all in the code says that it is supported... this is strange. Could you send me please your celerio config file and your pom file ?

**Comment by mreddimasi** [comment] 2016-01-25 15:34
<?xml version="1.0" encoding="UTF-8"?>
<celerio xmlns="http://www.jaxio.com/schema/celerio" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.jaxio.com/schema/celerio ./celerio.xsd">
    <configuration rootPackage="com.arvee.fuel" applicationName="fuel">

```
    <tables>

        <table include="true" pattern="*"/>
    </tables>
<sequences>
  <sequence tableNamePattern="*" sequenceName="{TABLE_NAME}_ID_SEQ" allocationSize="1" />
</sequences>


    <numberMappings>
        <numberMapping mappedType="M_BOOLEAN" columnSizeMin="1" columnSizeMax="2" columnDecimalDigitsMin="0"
                       columnDecimalDigitsMax="0"/>

    </numberMappings>


    <dateMappings>
        teMappings>


    <defaultEntityCacheConfig usage="NONE"/>

    <defaultManyToOneConfig fetch="LAZY">
        <cascades>
            <cascade type="PERSIST"/>
            <cascade type="MERGE"/>
        </cascades>
        <cacheConfig usage="NONE"/>
        <associationAction create="true" edit="true" view="true" select="true" autoComplete="true" remove="false"/>
    </defaultManyToOneConfig>

    <defaultOneToManyConfig orphanRemoval="true">
        <cascades>
            <cascade type="ALL"/>
        </cascades>
        <cacheConfig usage="NONE"/>
        <associationAction create="true" edit="true" view="true" select="true" autoComplete="true" remove="true"/>
    </defaultOneToManyConfig>

    <defaultOneToOneConfig fetch="LAZY">
        <cascades>
            <cascade type="NONE"/>
        </cascades>
        <cacheConfig usage="NONE"/>
        <associationAction create="true" edit="true" view="true" select="false" autoComplete="true" remove="false"/>
    </defaultOneToOneConfig>

    <defaultInverseOneToOneConfig fetch="LAZY">
        <cascades>
            <cascade type="ALL"/>
        </cascades>
        <cacheConfig usage="NONE"/>
        <associationAction create="false" edit="false" view="true" select="false" autoComplete="false"
                           remove="false"/>
    </defaultInverseOneToOneConfig>

    <defaultManyToManyConfig>
        <cascades>
            <cascade type="PERSIST"/>
            <cascade type="MERGE"/>
        </cascades>
        <cacheConfig usage="NONE"/>
        <associationAction create="true" edit="true" view="true" select="true" autoComplete="false" remove="true"/>
    </defaultManyToManyConfig>

    <defaultInverseManyToManyConfig>
        <cascades>
            <cascade type="ALL"/>
        </cascades>
        <cacheConfig usage="NONE"/>
        <associationAction create="false" edit="true" view="true" select="false" autoComplete="false"
                           remove="false"/>
    </defaultInverseManyToManyConfig>

    <conventions identifiableProperty="id">

    </conventions>
</configuration>

<entityConfigs>
  <entityConfig tableName="PO_DETAIL">
    <columnConfigs>
  <columnConfig columnName="PO_HEADER_ID" associationDirection="BIDIRECTIONAL" />
</columnConfigs>
  </entityConfig>
  <entityConfig tableName="PO_CHARGES">
    <columnConfigs>
  <columnConfig columnName="PO_HEADER_ID" associationDirection="BIDIRECTIONAL" />
  <columnConfig columnName="PO_DETAIL_ID" associationDirection="BIDIRECTIONAL" />
</columnConfigs>
 </entityConfig>
 <entityConfig tableName="RFQ_VENDOR">
   <columnConfigs>
     <columnConfig columnName="RFQ_HEADER_ID" associationDirection="BIDIRECTIONAL"/>
  </columnConfigs>
</entityConfig>
</entityConfigs>


<sharedEnumConfigs>
</sharedEnumConfigs>
```

</celerio>

**Comment by mreddimasi** [comment] 2016-01-25 15:36
<?xml version="1.0" encoding="UTF-8"?>

<!--
 ! Source code generated by Celerio, a Jaxio product.
 ! Documentation: http://www.jaxio.com/documentation/celerio/
 ! Follow us on twitter: @jaxiosoft
 ! Need commercial support ? Contact us: info@jaxio.com
 ! Template pack-backend-jpa:bootstrap/pom.boot.vm.xml
 ! Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.arvee.fuel</groupId>
    <artifactId>fuel</artifactId>
    <packaging>jar</packaging>
    <version>1.0.0-SNAPSHOT</version>
    <name>fuel</name>
    <properties>
        <!-- ~~~~~~~~ -->
        <!-- Database -->
        <!-- ~~~~~~~~ -->
        <!-- Note: during development using the same value for your login, password, database name and project name is really convenient -->
        <database.name>${project.name}</database.name>
        <database.host>localhost</database.host>
        <database.user>${project.name}</database.user>
        <database.password>${project.name}</database.password>

```
    <!-- **** CHANGE THE PROPERTIES BELOW TO USE YOUR OWN DATABASE **** -->
    <!-- **** DO NOT USE A PRODUCTION DATABASE **** -->
    <jdbc.type>oracle</jdbc.type><!-- see 'db' profile, it is used to find the sql script -->

    <jdbc.groupId>com.oracle</jdbc.groupId>
    <jdbc.artifactId>ojdbc6</jdbc.artifactId>
    <jdbc.version>11.2.0.4</jdbc.version>

    <!-- h2 jdbc settings -->
    <jdbc.driver>oracle.jdbc.driver.OracleDriver</jdbc.driver>
    <jdbc.url>jdbc:oracle:thin:@localhost:1521:XE</jdbc.url>
    <jdbc.user>fuel</jdbc.user>
    <jdbc.password>secret</jdbc.password>
    <jdbc.catalog></jdbc.catalog>
    <hibernate.dialect>org.hibernate.dialect.Oracle10gDialect</hibernate.dialect>
    <sql-maven-plugin.delimiter>;</sql-maven-plugin.delimiter>

    <!-- ~~~~~~ -->
    <!-- System -->
    <!-- ~~~~~~ -->
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!-- Version dependencies when used in multiple dependencies -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <celerio-maven-plugin.outputDir>${project.basedir}</celerio-maven-plugin.outputDir>
    <celerio-maven-plugin.version>4.0.2</celerio-maven-plugin.version>
    <hibernate.version>5.0.2.Final</hibernate.version>
    <spring.version>4.2.2.RELEASE</spring.version>
    <spring-security.version>4.0.2.RELEASE</spring-security.version>
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!-- Variables substituted in resources file at build time -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!-- logs -->
    <log.target>${project.build.directory}/logs</log.target>
    <log.level>DEBUG</log.level>
    <log.sql.queries.level>DEBUG</log.sql.queries.level>
    <!-- hibernate, see by src/main/resource/hibernate.properties -->
    <hibernate.show.sql>true</hibernate.show.sql>
    <hibernate.format.sql>true</hibernate.format.sql>
    <hibernate.generate_statistics>true</hibernate.generate_statistics>
    <hibernate.use_sql_comments>true</hibernate.use_sql_comments>
    <hibernate.ehcache.configuration.file>ehcache.xml</hibernate.ehcache.configuration.file>
    <hibernate.use.second.level.cache>true</hibernate.use.second.level.cache>
    <hibernate.use.query.cache>true</hibernate.use.query.cache>
</properties>
<profiles>
    <profile>
        <!-- ~~~~~~~~~~~~~~~~~~~ -->
        <!-- Disable debug modes -->
        <!-- ~~~~~~~~~~~~~~~~~~~ -->
        <id>perf</id>
        <properties>
            <hibernate.show.sql>false</hibernate.show.sql>
            <hibernate.format.sql>false</hibernate.format.sql>
            <hibernate.use_sql_comments>false</hibernate.use_sql_comments>
            <hibernate.generate_statistics>false</hibernate.generate_statistics>
            <log.level>WARN</log.level>
            <log.sql.queries.level>WARN</log.sql.queries.level>
        </properties>
    </profile>
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!-- Drop and recreate the database -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <profile>
        <id>db</id>
        <build>
            <defaultGoal>initialize</defaultGoal>
            <plugins>
                <plugin>
                    <!-- http://mojo.codehaus.org/sql-maven-plugin/ -->
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>sql-maven-plugin</artifactId>
                    <version>1.5</version>
                    <executions>
                        <execution>
                            <id>Create and initialize the database</id>
                            <phase>initialize</phase>
                            <configuration>
                                <driver>${jdbc.driver}</driver>
                                <url>${jdbc.url}</url>
                                <username>${jdbc.user}</username>
                                <password>${jdbc.password}</password>
                                <autocommit>true</autocommit>
                                <encoding>UTF-8</encoding>
                                <printResultSet>true</printResultSet>
                                <onError>continue</onError>
                                <delimiter>${sql-maven-plugin.delimiter}</delimiter>
                                <orderFile>ascending</orderFile>
                                <fileset>
                                    <basedir>${project.basedir}</basedir>
                                    <includes>
                                        <include>src/main/sql/${jdbc.type}/*.sql</include>
                                    </includes>
                                </fileset>
                            </configuration>
                            <goals>
                                <goal>execute</goal>
                            </goals>
                        </execution>
                    </executions>
                    <dependencies>
                        <dependency>
                            <groupId>${jdbc.groupId}</groupId>
                            <artifactId>${jdbc.artifactId}</artifactId>
                            <version>${jdbc.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
            </plugins>
        </build>
    </profile>
    <!-- Profiles below are used when Celerio Maven Plugin is present in the build process -->
    <profile>
        <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
        <!-- Extract the database metadata -->
        <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
        <id>metadata</id>
        <build>
            <defaultGoal>generate-sources</defaultGoal>
            <plugins>
                <plugin>
                    <groupId>com.jaxio.celerio</groupId>
                    <artifactId>dbmetadata-maven-plugin</artifactId>
                    <version>${celerio-maven-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>Extract the database schema.</id>
                            <goals>
                                <goal>extract-metadata</goal>
                            </goals>
                        </execution>
                    </executions>
                    <dependencies>
                        <dependency>
                            <groupId>${jdbc.groupId}</groupId>
                            <artifactId>${jdbc.artifactId}</artifactId>
                            <version>${jdbc.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
            </plugins>
        </build>
    </profile>
    <profile>
        <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
        <!-- Generate the code using Celerio -->
        <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
        <id>gen</id>
        <build>
            <defaultGoal>generate-sources</defaultGoal>
            <plugins>
                <plugin>
                    <groupId>com.jaxio.celerio</groupId>
                    <artifactId>celerio-maven-plugin</artifactId>
                    <version>${celerio-maven-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>Generates files using the extracted database schema.</id>
                            <goals>
                                <goal>generate</goal>
                            </goals>
                        </execution>
                    </executions>
                    <dependencies>
                        <dependency>
                            <groupId>com.jaxio.celerio.packs</groupId>
                            <artifactId>pack-backend-jpa</artifactId>
                            <version>1.0.2</version>
                        </dependency>
                    </dependencies>
                </plugin>
            </plugins>
        </build>
    </profile>
    <profile>
        <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
        <!-- Delete code generated by Celerio -->
        <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
        <id>cleanGen</id>
        <build>
            <plugins>
                <plugin>
                    <groupId>com.jaxio.celerio</groupId>
                    <artifactId>celerio-maven-plugin</artifactId>
                    <version>${celerio-maven-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>Delete previously generated files (use .celerio/ folder)</id>
                            <goals>
                                <goal>cleanGenerated</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </build>
    </profile>
</profiles>
<!-- ~~~~~~~~~~~~ -->
<!-- DEPENDENCIES -->
<!-- ~~~~~~~~~~~~ -->
<dependencies>
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!-- List your specific dependencies below -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!-- Dependencies needed by the generated project -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

    <!-- ~~~~~~~~~~~ -->
    <!-- PERSISTENCE -->
    <!-- ~~~~~~~~~~~ -->

    <!-- https://github.com/jaxio/jpa-query-by-example -->
    <dependency>
        <groupId>com.jaxio</groupId>
        <artifactId>jpa-querybyexample</artifactId>
        <version>1.0.1</version>
    </dependency>

    <dependency>
        <groupId>org.hibernate.javax.persistence</groupId>
        <artifactId>hibernate-jpa-2.1-api</artifactId>
        <version>1.0.0.Final</version>
    </dependency>
    <dependency>
        <groupId>org.hibernate</groupId>
        <artifactId>hibernate-core</artifactId>
        <version>${hibernate.version}</version>
    </dependency>
    <dependency>
        <groupId>org.hibernate</groupId>
        <artifactId>hibernate-ehcache</artifactId>
        <version>${hibernate.version}</version>
    </dependency>
    <dependency>
        <groupId>org.hibernate</groupId>
        <artifactId>hibernate-entitymanager</artifactId>
        <version>${hibernate.version}</version>
    </dependency>
    <dependency>
        <groupId>org.hibernate</groupId>
        <artifactId>hibernate-java8</artifactId>
        <version>${hibernate.version}</version>
    </dependency>
    <dependency>
        <groupId>cglib</groupId>
        <artifactId>cglib</artifactId>
        <version>3.1</version>
        <scope>runtime</scope>
    </dependency>
    <dependency>
        <groupId>org.apache.tomcat</groupId>
        <artifactId>tomcat-jdbc</artifactId>
        <version>8.0.28</version>
        <exclusions>
            <exclusion>
                <groupId>org.apache.tomcat</groupId>
                <artifactId>tomcat-juli</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>${jdbc.groupId}</groupId>
        <artifactId>${jdbc.artifactId}</artifactId>
        <version>${jdbc.version}</version>
    </dependency>
    <!-- ~~~~~~~~~~~~~~~~ -->
    <!-- HIBERNATE SEARCH -->
    <!-- ~~~~~~~~~~~~~~~~ -->
    <dependency>
        <groupId>org.hibernate</groupId>
        <artifactId>hibernate-search-orm</artifactId>
        <version>5.5.0.Final</version>
        </dependency>
    <dependency>
        <groupId>org.apache.solr</groupId>
        <artifactId>solr-common</artifactId>
        <version>1.3.0</version>
    </dependency>
    <dependency>
        <groupId>org.apache.solr</groupId>
        <artifactId>solr-core</artifactId>
        <version>5.3.1</version>
    </dependency>
    <dependency>
        <groupId>org.apache.tika</groupId>
        <artifactId>tika-parsers</artifactId>
        <version>1.11</version>
        <exclusions>
            <exclusion>
                <artifactId>commons-logging</artifactId>
                <groupId>commons-logging</groupId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>org.codehaus.jackson</groupId>
        <artifactId>jackson-mapper-asl</artifactId>
        <version>1.9.13</version>
    </dependency>
    <!-- ~~~~~~~~~~ -->
    <!-- VALIDATION -->
    <!-- ~~~~~~~~~~ -->
    <dependency>
        <groupId>javax.validation</groupId>
        <artifactId>validation-api</artifactId>
        <version>1.1.0.Final</version>
    </dependency>
    <dependency>
        <groupId>org.hibernate</groupId>
        <artifactId>hibernate-validator</artifactId>
        <version>5.2.2.Final</version>
    </dependency>
    <!--Hibernate Validator requires an implementation of the Unified Expression Language (JSR 341) -->
    <dependency>
        <groupId>javax.el</groupId>
        <artifactId>javax.el-api</artifactId>
        <version>2.2.4</version>
    </dependency>
    <dependency>
        <groupId>org.glassfish.web</groupId>
        <artifactId>javax.el</artifactId>
        <version>2.2.4</version>
    </dependency>
    <dependency> <!-- validation html -->
        <groupId>org.jsoup</groupId>
        <artifactId>jsoup</artifactId>
        <version>1.8.3</version>
    </dependency>
    <!-- ~~~~~~ -->
    <!-- LOGGER -->
    <!-- ~~~~~~ -->
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>1.7.12</version>
    </dependency>
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>log4j-over-slf4j</artifactId>
        <version>1.7.12</version>
    </dependency>
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>jcl-over-slf4j</artifactId>
        <version>1.7.12</version>
    </dependency>
    <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
        <version>1.1.3</version>
    </dependency>
    <!-- ~~~~~ -->
    <!-- UTILS -->
    <!-- ~~~~~ -->
    <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>18.0</version>
    </dependency>
    <dependency>
        <groupId>commons-io</groupId>
        <artifactId>commons-io</artifactId>
        <version>2.4</version>
    </dependency>
    <dependency>
        <groupId>commons-lang</groupId>
        <artifactId>commons-lang</artifactId>
        <version>2.6</version>
    </dependency>
    <dependency>
        <groupId>commons-fileupload</groupId>
        <artifactId>commons-fileupload</artifactId>
        <version>1.3.1</version>
    </dependency>
    <dependency>
        <groupId>commons-codec</groupId>
        <artifactId>commons-codec</artifactId>
        <version>1.10</version>
    </dependency>
    <dependency>
        <groupId>commons-beanutils</groupId>
        <artifactId>commons-beanutils</artifactId>
        <version>1.9.2</version>
        <exclusions>
            <exclusion>
                <artifactId>commons-logging</artifactId>
                <groupId>commons-logging</groupId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>commons-collections</groupId>
        <artifactId>commons-collections</artifactId>
        <version>3.2.1</version>
    </dependency>
    <!-- ~~~~~~ -->
    <!-- SPRING -->
    <!-- ~~~~~~ -->
    <dependency>
        <groupId>javax.inject</groupId>
        <artifactId>javax.inject</artifactId>
        <version>1</version>
    </dependency>
    <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-context</artifactId>
        <version>${spring.version}</version>
        <exclusions>
            <exclusion>
                <artifactId>commons-logging</artifactId>
                <groupId>commons-logging</groupId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-expression</artifactId>
        <version>${spring.version}</version>
    </dependency>
    <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-jdbc</artifactId>
        <version>${spring.version}</version>
    </dependency>
    <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-orm</artifactId>
        <version>${spring.version}</version>
    </dependency>
    <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-aspects</artifactId>
        <version>${spring.version}</version>
    </dependency>
    <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-aop</artifactId>
        <version>${spring.version}</version>
    </dependency>
    <dependency>
        <groupId>org.aspectj</groupId>
        <artifactId>aspectjrt</artifactId>
        <version>1.8.7</version>
    </dependency>
    <dependency>
        <groupId>org.aspectj</groupId>
        <artifactId>aspectjweaver</artifactId>
        <version>1.8.7</version>
    </dependency>
    <!-- ~~~~~~~~~~~~~~~ -->
    <!-- SPRING SECURITY -->
    <!-- ~~~~~~~~~~~~~~~ -->
    <dependency>
        <groupId>javax.annotation</groupId>
        <artifactId>jsr250-api</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>org.springframework.security</groupId>
        <artifactId>spring-security-core</artifactId>
        <version>${spring-security.version}</version>
    </dependency>
    <dependency>
        <groupId>org.springframework.security</groupId>
        <artifactId>spring-security-web</artifactId>
        <version>${spring-security.version}</version>
    </dependency>
    <dependency>
        <groupId>org.springframework.security</groupId>
        <artifactId>spring-security-acl</artifactId>
        <version>${spring-security.version}</version>
    </dependency>
    <dependency>
        <groupId>org.springframework.security</groupId>
        <artifactId>spring-security-config</artifactId>
        <version>${spring-security.version}</version>
    </dependency>
    <!-- ~~~~~~~~~~ -->
    <!-- MONITORING -->
    <!-- ~~~~~~~~~~ -->
    <dependency>
        <groupId>net.bull.javamelody</groupId>
        <artifactId>javamelody-core</artifactId>
        <version>1.57.0</version>
    </dependency>
    <!-- ~~~~ -->
    <!-- TEST -->
    <!-- ~~~~ -->
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.12</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-all</artifactId>
        <version>1.10.19</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.easytesting</groupId>
        <artifactId>fest-assert</artifactId>
        <version>1.4</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-test</artifactId>
        <version>${spring.version}</version>
        <scope>test</scope>
    </dependency>
</dependencies>
<!-- ~~~~~~~~~~~~ -->
<!-- REPOSITORIES -->
<!-- ~~~~~~~~~~~~ -->
<pluginRepositories>
    <pluginRepository>
        <id>Codehaus Snapshots</id>
        <url>https://nexus.codehaus.org/content/repositories/releases</url>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
<repositories>
    <repository>
        <id>jboss</id>
        <url>http://repository.jboss.org/nexus/content/groups/public-jboss</url>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>

<!-- ~~~~~ -->
<!-- BUILD -->
<!-- ~~~~~ -->
<build>
    <defaultGoal>test</defaultGoal>
    <resources>
        <resource>
            <directory>${celerio-maven-plugin.outputDir}/src/main/resources</directory>
            <filtering>true</filtering>
        </resource>
        <resource>
            <directory>src/main/resources</directory>
            <filtering>true</filtering>
        </resource>
    </resources>
    <testResources>
        <testResource>
            <directory>${celerio-maven-plugin.outputDir}/src/test/resources</directory>
            <filtering>true</filtering>
        </testResource>
        <testResource>
            <directory>src/test/resources</directory>
            <filtering>true</filtering>
        </testResource>
    </testResources>
    <plugins>
        <plugin>
            <!-- http://maven.apache.org/plugins/maven-resources-plugin/ -->
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-resources-plugin</artifactId>
            <version>2.7</version>
            <configuration>
                <delimiters>
                    <delimiter>@*@</delimiter>
                </delimiters>
                <useDefaultDelimiters>false</useDefaultDelimiters>
                <nonFilteredFileExtensions>
                    <nonFilteredFileExtension>xls</nonFilteredFileExtension>
                    <nonFilteredFileExtension>xlsx</nonFilteredFileExtension>
                    <nonFilteredFileExtension>pdf</nonFilteredFileExtension>
                </nonFilteredFileExtensions>
            </configuration>
        </plugin>
        <plugin>
            <!-- http://maven.apache.org/plugins/maven-compiler-plugin/ -->
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.3</version>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
                <compilerArgument>-Xlint</compilerArgument>
                <showWarnings>true</showWarnings>
                <showDeprecation>true</showDeprecation>
            </configuration>
        </plugin>
        <plugin>
            <!-- http://mojo.codehaus.org/build-helper-maven-plugin/ -->
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
            <version>1.9.1</version>
            <executions>
                <execution>
                    <id>Adding generated java folder to build</id>
                    <phase>generate-sources</phase>
                    <goals>
                        <goal>add-source</goal>
                    </goals>
                    <configuration>
                        <sources>
                            <source>${celerio-maven-plugin.outputDir}/src/main/java</source>
                            <source>${celerio-maven-plugin.outputDir}/src/main/generated-java</source>
                        </sources>
                    </configuration>
                </execution>
                <execution>
                    <id>Adding generated java test location to test build</id>
                    <phase>generate-sources</phase>
                    <goals>
                        <goal>add-test-source</goal>
                    </goals>
                    <configuration>
                        <sources>
                            <source>${celerio-maven-plugin.outputDir}/src/test/java</source>
                            <source>${celerio-maven-plugin.outputDir}/src/test/generated-java</source>
                        </sources>
                    </configuration>
                </execution>
            </executions>
        </plugin>
        <plugin>
            <!-- http://maven.apache.org/plugins/maven-install-plugin/ -->
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-install-plugin</artifactId>
            <version>2.5.2</version>
        </plugin>
        <plugin>
            <!-- http://maven.apache.org/plugins/maven-clean-plugin/ -->
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-clean-plugin</artifactId>
            <version>2.6.1</version>
        </plugin>
        <plugin>
            <!-- http://maven.apache.org/plugins/maven-surefire-plugin/ -->
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.18.1</version>
            <configuration>
                <!-- surefire uses a new jvm, MAVEN_OPTS are ignored, so you better set the memory options here -->
                <argLine>-Xmx512m -XX:MaxPermSize=256m</argLine>
            </configuration>
        </plugin>
        <plugin>
            <!-- http://maven.apache.org/plugins/maven-failsafe-plugin/ -->
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>2.18.1</version>
            <executions>
                <execution>
                    <id>integration-test</id>
                    <goals>
                        <goal>integration-test</goal>
                    </goals>
                </execution>
                <execution>
                    <id>verify</id>
                    <goals>
                        <goal>verify</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
        <plugin>
            <!-- http://maven.apache.org/plugins/maven-release-plugin/ -->
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-release-plugin</artifactId>
            <version>2.5.2</version>
            <configuration>
                <arguments>-Pdb,metadata,gen</arguments>
                <releaseProfiles>db,metadata,gen</releaseProfiles>
            </configuration>
        </plugin>
    </plugins>
</build>
```

</project>

**Comment by mreddimasi** [comment] 2016-01-25 15:36
Sorry unable to upload files for some reason, have pasted the config and pom file

**Comment by nromanetti** [comment] 2016-01-25 15:38
no pb. On current version of celerio we have indeed a bug, in case allocationSize is 1, we do not take it into account (as we consider by mistake that 1 is the default value, whereas in fact 50 is the default value). This will be fixed. Thanks.

**Comment by mreddimasi** [comment] 2016-01-25 15:48
Thank You so much Nicolas

**Closed as completed** 2016-01-25 15:55 UTC

**Comment by nromanetti** [comment] 2016-01-25 21:14
Please try with latest celerio release, version 4.0.4

**Comment by jaydubu** [comment] 2016-01-27 11:43
It is working now. Thanks!
